---
title       : Second part of Final assignment for DDP
subtitle    : 
author      : Gabdolla Azat
job         : Data Scientis
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---
Shiny app pitch

I have created simple shiny app that include only one page with three functions

 1. Histogram plotter to randomly generated normally distributed sample
 2. Text input that will render input text on another box 
 3. Ready button that generate the ouptut


--- .class #id 
App info:

Date of upload: 23.01.2019

App uploaded and installed to shinyapps, available 
      by this link: https://azat.shinyapps.io/ddp4/

Code used to develop app is available 
     by this link https://github.com/AzatG/developing-data-products


--- .class #id

Shiny educational resources 

Shiny is package used to create data driven apps.

Intro to Shiny tutorial: https://shiny.rstudio.com/tutorial/

I also recommend to look at Shinydashboard package  

Shinydashboard : https://rstudio.github.io/shinydashboard/  

Shiny gallery (bank of applications)  https://shiny.rstudio.com/gallery/

--- .class #id

Personal experience of using Shiny apps

PROS:  
1. Easy to develop  
2. All R outputs can be rendered in app  
3. Free    
   

CONS:  
1. Not popular   
2. Sometimes memory inefficient  



